name: fe-cd-prod
on:
  workflow_run:
    workflows: [ "fe-ci-prod" ]
    types:
      - completed
  workflow_dispatch:


jobs:
  deploy-prod:
    runs-on: [self-hosted, production]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_HASH_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_HASH_PAT }}

      - name: Checkout Compose Repo
        uses: actions/checkout@v4
        with:
          repository: meogle-share/blog-infra
          ref: main
          path: blog-infra
          token: ${{ secrets.GIT_HUB_HASH_PAT }}

      - name: Deploy UI Service
        working-directory: blog-infra
        run: |
          docker compose -p meogle -f docker-compose.yml -f docker-compose.prod.yml pull ui
          docker compose -p meogle -f docker-compose.yml -f docker-compose.prod.yml up -d ui autoheal

      - name: Clean up dangling images
        if: success()
        run: |
          docker image prune -f
